# Generated by Django 2.1.2 on 2019-01-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiarc_registration', '0003_auto_20190124_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiarcuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hiarcuser',
            name='last_name',
        ),
    ]
