# Generated by Django 2.1.2 on 2019-01-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiarc_registration', '0004_auto_20190125_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiarcuser',
            name='blog_url',
            field=models.CharField(blank=True, max_length=20, verbose_name='blog_url'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='boj_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='boj_id'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='codeforces_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='codeforces_id'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='github_id'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='topcoder_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='topcoder_id'),
        ),
    ]
