# Generated by Django 2.1.2 on 2019-01-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiarc_registration', '0006_auto_20190126_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiarcuser',
            name='comment',
            field=models.TextField(default='', verbose_name='comment'),
            preserve_default=False,
        ),
    ]
